#!/bin/sh
#
# "post-update" hook script to prepare a packed repository for use over
# dump transports (i.e. http).
#
# Copyright (c) 2009 Benedikt Meurer <benedikt.meurer@googlemail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#

exec git-update-server-info
